# Generated by Django 5.0.6 on 2024-12-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
